spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mygroupId
#      關閉offset自動提交
      enable-auto-commit: false
      properties:
        interceptor:
          classes: com.example.interceptor.CustomConsumerInterceptor
    producer:
#    註冊事務功能
      transaction-id-prefix: tx-
      properties:
        interceptor:
          classes: com.example.interceptor.CustomProducerInterceptor
#    ack手動提交
    listener:
      ack-mode: manual